import Footer from "./component/footer";
import Navbar from "./component/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OFashion Store",
  description: "Generated by Ahmad Bilal Farooqi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-mywhite max-w-[90%] mx-auto`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
